name: CreateFramework
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Simulator XCFramework
        run: |
          xcodebuild archive \
          -scheme CICDFramework \
          -configuration Release \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath './archives/Framework-Simulator' \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES
      - name: Build Device XCFramework
        run: |
          xcodebuild archive \
          -scheme CICDFramework \
          -configuration Release \
          -destination 'generic/platform=iOS’ \
          -archivePath './archives/Framework' \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES
      - name: Build Universal XCFramework
        run: |
          xcodebuild -create-xcframework \
          -framework archives/Framework.xcarchive/Products/Library/Frameworks/CICDFramework.framework \
          -framework archives/Framework-Simulator.xcarchive/Products/Library/Frameworks/CICDFramework.framework \
          -output ./CICDFramework.xcframework
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Added framework"
          git push
