name: CreateFramework
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Simulator XCFramework
        run: |
          xcodebuild archive \
          -scheme FrameworkCICD \
          -configuration Release \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath './archives/Framework-Simulator' \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES
      - name: Delete Existing Framewok
        run: |
          rm -rf ./FrameworkCICD.xcframework
      - name: Build Universal XCFramework
        run: |
          xcodebuild -create-xcframework \
          -framework archives/Framework-Simulator.xcarchive/Products/Library/Frameworks/FrameworkCICD.framework \
          -output ./FrameworkCICD.xcframework
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Added framework"
          git push
      - name: Delete Archives
        run: |
            rm -rf ./archives
